intro:
  steps:
    1:
      title: "Pourquoi c'est important de catégoriser tes dépenses ?"
      text: "Une dépense non catégorisée n'est pas prise en compte dans le calcul de ton impact : tu augmentes donc ta précision en catégorisant un maximum de dépenses."
    2:
      title: "Comment catégoriser tes dépenses ?"
      text: "Choisi la catégorie qui décrit le mieux cette dépense dans la liste déroulante : tu peux également filtrer cette liste de catégories pour aller plus vite."
    3:
      title: "Une catégorisation de plus en plus intelligente"
      text: "Lorsque tu catégorises une dépense tu améliores le système pour tout le monde, alors merci ! Une fois une dépense catégorisée, nous suggérons la même catégorie pour les dépenses similaires d'autres utilisateurs : c'est pour ça que tu n'as besoin que de valider notre suggestion pour catégoriser certaines dépenses (et de plus en plus)."


